<div class="navbar navbar-inverse" role="navigation">
  <div class="container">
	<?php echo $this->action('navigation','index')?>
  </div><!-- /.container -->
</div><!-- /.navbar -->

<h1>Alterar produto</h1>

<form name="formProduto" id="formProduto" method="post" action="<?php echo $this->url(array('controller' => 'gerenciar-produtos', 'action' => 'alterar')); ?>">
    <table class="form">
        <tr>
            <td><?php echo $this->form->fk_categoria->getLabel();?></td>
            <td>
                <?php echo $this->form->fk_categoria?>
                <?php if($this->form->fk_categoria->getMessages()):?>
                    <div class="errors">
                        <?php echo current($this->form->fk_categoria->getMessages())?>
                    </div>
                <?php endif; ?>
            </td>
        </tr>
        
        <tr>
            <td><?php echo $this->form->desc_produto->getLabel()?></td>
            <td>
                <?php echo $this->form->desc_produto?>
                <?php if($this->form->desc_produto->getMessages()):?>
                    <div class="errors">
                        <?php echo current($this->form->desc_produto->getMessages())?>
                    </div>
                <?php endif; ?>
            </td>
        </tr>
        <tr>
        	<td><?php echo $this->form->vlr_preco->getLabel()?></td>
            <td>
                <?php echo $this->form->vlr_preco?>
                <?php if($this->form->vlr_preco->getMessages()):?>
                    <div class="errors">
                        <?php echo current($this->form->vlr_preco->getMessages())?>
                    </div>
                <?php endif; ?>
            </td>
        </tr>

        <tr>
            <td><?php echo $this->form->promocao_produto->getLabel()?></td>
            <td>
                <?php echo $this->form->promocao_produto?>
                <?php if($this->form->promocao_produto->getMessages()):?>
                    <div class="errors">
                        <?php echo current($this->form->promocao_produto->getMessages())?>
                    </div>
                <?php endif; ?>
            </td>
        </tr>

        <tr>
            <td><?php echo $this->form->porcentagem_produto->getLabel()?></td>
            <td>
                <?php echo $this->form->porcentagem_produto?>
                <?php if($this->form->porcentagem_produto->getMessages()):?>
                    <div class="errors">
                        <?php echo current($this->form->porcentagem_produto->getMessages())?>
                    </div>
                <?php endif; ?>
            </td>
        </tr>

        <tr>
            <td></td>
            <td>
                <button type="button" class="btn" onclick="document.location.href='<?php echo $this->url(array('controller' => 'gerenciar-produtos', 'action' => 'index')); ?>'">Cancelar</button>
                <button type="submit" class="btn">Alterar</button>
            </td>
        </tr>
    </table>
</form>