   <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container">
		<?php echo $this->action('navigation','index', array('page' => $this->page))?>
      </div><!-- /.container -->
    </div><!-- /.navbar -->

    <div class="container">

      <div class="row row-offcanvas row-offcanvas-right">
        <div class="col-xs-12 col-sm-9">
          <div class="jumbotron">
            <h1>Gráfica Teste</h1>
            <p>Confira a lista de Categorias.</p>
          </div>
          <div class="row">
            <div class="col-6 col-sm-6 col-lg-4">
              <h2>Categoria 1</h2>
              <p>Valor: a partir de R$ 5,00</p>
              <p><a class="btn btn-default" href="<?php echo $this->url(array('controller'=>'index', 'action'=>'listar','id'=>1))?>">Mais detalhes &raquo;</a></p>
            </div><!--/span-->

            <div class="col-6 col-sm-6 col-lg-4">
              <h2>Categoria 2</h2>
               <p>Valor: a partir de R$ 15,00</p>
              <p><a class="btn btn-default" href="<?php echo $this->url(array('controller'=>'index', 'action'=>'listar','id'=>2))?>">Mais detalhes &raquo;</a></p>
            </div><!--/span-->

            <div class="col-6 col-sm-6 col-lg-4">
              <h2>Categoria 3</h2>
               <p>Valor: a partir de R$ 12,00</p>
              <p><a class="btn btn-default" href="<?php echo $this->url(array('controller'=>'index', 'action'=>'listar','id'=>3))?>">Mais detalhes &raquo;</a></p>
            </div><!--/span-->

           <div class="col-6 col-sm-6 col-lg-4">
              <h2>Categoria 4</h2>
               <p>Valor: a partir de R$ 25,00</p>
              <p><a class="btn btn-default" href="#">Mais detalhes &raquo;</a></p>
            </div><!--/span-->

            <div class="col-6 col-sm-6 col-lg-4">
              <h2>Categoria 5</h2>
               <p>Valor: a partir de R$ 14,00</p>
              <p><a class="btn btn-default" href="#">Mais detalhes &raquo;</a></p>
            </div><!--/span-->

            <div class="col-6 col-sm-6 col-lg-4">
              <h2>Categoria 6</h2>
               <p>Valor: a partir de R$ 18,00</p>
              <p><a class="btn btn-default" href="#">Mais detalhes &raquo;</a></p>
            </div><!--/span-->

          </div><!--/row-->
        </div><!--/span-->

        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
			<?php echo $this->action('menu-lateral','index')?>
        </div><!--/span-->
      </div><!--/row-->

      <hr>

      <footer>
        <p>&copy; Atualcard 2013</p>
      </footer>

    </div><!--/.container-->
<?php
$this->headScript()->appendFile( $this->baseUrl().'/skin/classic/offcanvas/js/html5shiv.js',	'text/javascript',	array('conditional' => 'lt IE 9'));
$this->headScript()->appendFile( $this->baseUrl().'/skin/classic/offcanvas/js/respond.min.js',	'text/javascript',	array('conditional' => 'lt IE 9'));
$this->headScript()->appendFile( $this->baseUrl().'/skin/classic/offcanvas/js/offcanvas.js',	'text/javascript');
$this->headLink()->appendStylesheet( $this->baseUrl().'/skin/classic/offcanvas/css/offcanvas.css','screen');
?>
