   <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container">
		<?php echo $this->action('navigation','index', array('page' => $this->page))?>
      </div><!-- /.container -->
    </div><!-- /.navbar -->

    <div class="container">

      <div class="row row-offcanvas row-offcanvas-right">
        <div class="col-xs-12 col-sm-9">
          <div class="jumbotron">
            <h1>Gráfica Teste</h1>
            <p>Confira a lista de Categorias.</p>
          </div>
          <div class="row">
          <?php foreach($this->page as $item):?>
            <div class="col-6 col-sm-6 col-lg-4">
              <h2><?php echo $item['desc_categoria'];?></h2>
              <p><?php echo $item['desc_categoria']. " " . $item['desc_produto'];?></p>
              <p>Valor: a partir de R$ <?php echo $item['vlr_preco'];?></p>
              <p><a class="btn btn-default" href="<?php echo $this->url(array('controller'=>'index', 'action'=>'listar','id'=>$item['pk_categoria']))?>">Mais detalhes &raquo;</a></p>
            </div><!--/span-->
          <?php endforeach;?>

          </div><!--/row-->
        </div><!--/span-->

        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
			
        </div><!--/span-->
      </div><!--/row-->

      <hr>

      <footer>
        <p>&copy; Atualcard 2013</p>
      </footer>

    </div><!--/.container-->
<?php
$this->headScript()->appendFile( $this->baseUrl().'/skin/classic/offcanvas/js/html5shiv.js',	'text/javascript',	array('conditional' => 'lt IE 9'));
$this->headScript()->appendFile( $this->baseUrl().'/skin/classic/offcanvas/js/respond.min.js',	'text/javascript',	array('conditional' => 'lt IE 9'));
$this->headScript()->appendFile( $this->baseUrl().'/skin/classic/offcanvas/js/offcanvas.js',	'text/javascript');
$this->headLink()->appendStylesheet( $this->baseUrl().'/skin/classic/offcanvas/css/offcanvas.css','screen');
?>
