   <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container">
		<?php echo $this->action('navigation','index')?>
      </div><!-- /.container -->
    </div><!-- /.navbar -->

    <div class="container">

      <div class="row row-offcanvas row-offcanvas-right">
        <div class="col-xs-12 col-sm-8">

          <div class="row">
			<table class="table table-striped">
				<tr>
					<th>Produto</th>
					<th>Valor</th>
					<th style="width: 100px">&nbsp;</th>
				</tr>
				<?php if(!empty($this->page)): ?>
					<?php foreach($this->page as $item):?>
					<tr>
						<td><?php echo $item['desc_produto'];?></td>

						<td><?php if(!empty($item['dta_validade_preco']) && $item['dta_validade_preco'] != null && date('Y-m-d') <= $item['dta_validade_preco']){
							$promocao = $item['vlr_preco'] / 100 * 20;
							$resultado = $item['vlr_preco'] - $promocao;
							echo "De : <span style='text-decoration: line-through;'>R$".$item['vlr_preco'] ."</span><br /> Por: R$".$resultado;
						}else{
							if(!empty($item['vlr_preco'])) {
								echo "R$".$item['vlr_preco'];
							}else{
								echo "Valor Indisponivel !";
							}
							}?></td>
						<td> <a href="#" class="btn btn-success btn-lg ">Comprar</a></td>
					</tr>
					<?php endforeach;?>
				<?php else: ?>
					<tr>
						<td>Nao ha promocao para esta data.</td>
					</tr>
				<?php endif; ?>
			</table>

          </div><!--/row-->
        </div><!--/span-->

        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
          <?php echo $this->action('menu-lateral','index')?>
        </div><!--/span-->
      </div><!--/row-->

      <hr>

      <footer>
        <p>&copy; Atualcard 2013</p>
      </footer>

    </div><!--/.container-->
<?php
$this->headScript()->appendFile( $this->baseUrl().'/skin/classic/offcanvas/js/html5shiv.js',	'text/javascript',	array('conditional' => 'lt IE 9'));
$this->headScript()->appendFile( $this->baseUrl().'/skin/classic/offcanvas/js/respond.min.js',	'text/javascript',	array('conditional' => 'lt IE 9'));
$this->headScript()->appendFile( $this->baseUrl().'/skin/classic/offcanvas/js/offcanvas.js',	'text/javascript');
$this->headLink()->appendStylesheet( $this->baseUrl().'/skin/classic/offcanvas/css/offcanvas.css','screen');
?>
