   <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">TESTE</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Produtos</a></li>
            <li><a href="#contact">Instruções</a></li>
          </ul>
        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
    </div><!-- /.navbar -->

    <div class="container">

      <div class="row row-offcanvas row-offcanvas-right">
        <div class="col-xs-12 col-sm-9">
          <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
          </p>
          <div class="jumbotron">
            <h1>Gráfica Teste</h1>
            <p>Confira a lista de produtos.</p>
          </div>
          <div class="row">

           <?php $this->headTitle('Error'); ?>

			<?php if ('development' == APPLICATION_ENV): ?>

			  <h3>Informação da Exceção:</h3>
			  	<h2><?php echo $this->message ?></h2>

				<p><b>Message:</b> <?php echo $this->exception->getMessage() ?></p>

				<h3>Stack trace:</h3>
				<pre><?php echo $this->exception->getTraceAsString() ?> </pre>

				<h3>Request Parameters:</h3>
				<pre><?php var_dump($this->request->getParams()) ?></pre>
			<?php endif ?>

          </div><!--/row-->
        </div><!--/span-->

        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
          <div class="well sidebar-nav">
            <ul class="nav">
              <li>Sidebar</li>
              <li class="active"><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li>Sidebar</li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li>Sidebar</li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <hr>

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div><!--/.container-->
<?php
$this->headScript()->appendFile('skin/classic/offcanvas/js/html5shiv.js',	'text/javascript',	array('conditional' => 'lt IE 9'));
$this->headScript()->appendFile('skin/classic/offcanvas/js/respond.min.js',	'text/javascript',	array('conditional' => 'lt IE 9'));
$this->headScript()->appendFile('skin/classic/offcanvas/js/offcanvas.js',	'text/javascript');
$this->headLink()->appendStylesheet('skin/classic/offcanvas/css/offcanvas.css','screen');
?>
